# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
