# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_class',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_class',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
