# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20160201_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=200, null=True)),
                ('unit_price', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(verbose_name=b'now')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('inferior_to', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default='2016-02-01 14:48:16.932973', verbose_name=b'now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchs', to='item.Item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='item.Item'),
        ),
    ]
