# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20160201_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
