# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20160201_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_id']},
        ),
    ]
