# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realm', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('bid', models.PositiveIntegerField()),
                ('buyout', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('timeLeft', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name=b'now')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realm.Realm')),
            ],
        ),
    ]
