# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='item.Item'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='realm.Realm'),
        ),
    ]
