# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20160201_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
